### ISSUE TITLE
node-base64 will not install with NPM due to base64 errors on Ubuntu 10.10 32bit, Node 0.4.2

### ISSUE THREAD

**Issue by Zenwolf** [pkrumins/node-base64#12]
npm info it worked if it ends with ok
npm info using npm@0.3.15
npm info using node@v0.4.2
npm info preinstall base64@2.0.2
npm info install base64@2.0.2
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /home/foouser/.node_libs 
Checking for node prefix                 : ok /home/foouser/.node 
'configure' finished successfully (0.140s)
Waf: Entering directory `/home/foouser/.node_libs/.npm/base64/2.0.2/package/build'
[1/2] cxx: base64.cc -> build/default/base64_1.o
../base64.cc: In function ‘v8::Handle<v8::Value> base64_encode_binding(const v8::Arguments&)’:
../base64.cc:138: error: ‘malloc’ was not declared in this scope
../base64.cc:141: error: ‘free’ was not declared in this scope
Waf: Leaving directory`/home/foouser/.node_libs/.npm/base64/2.0.2/package/build'
Build failed:  -> task failed (err #1): 
    {task: cxx base64.cc -> base64_1.o}
npm info base64@2.0.2 Failed to exec install script
npm ERR! install failed Error: base64@2.0.2 install: `node-waf configure build`
npm ERR! install failed `sh "-c" "node-waf configure build"` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/home/foouser/.node_libs/.npm/npm/0.3.15/package/lib/utils/exec.js:49:20)
npm ERR! install failed     at ChildProcess.emit (events.js:45:17)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:171:12)
npm info install failed rollback
npm info uninstall [ 'base64@2.0.2' ]
npm info preuninstall base64@2.0.2
npm info uninstall base64@2.0.2
npm info auto-deactive not symlink
npm info postuninstall base64@2.0.2
npm info uninstall base64@2.0.2 complete
npm info install failed rolled back
npm ERR! Error: base64@2.0.2 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/home/foouser/.node_libs/.npm/npm/0.3.15/package/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:45:17)
npm ERR!     at ChildProcess.onexit (child_process.js:171:12)
npm ERR! 
npm ERR! Failed at the base64@2.0.2 install script.
npm ERR! This is most likely a problem with the base64 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls base64
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.35-28-generic
npm ERR! argv { remain: [ 'base64' ],
npm ERR! argv   cooked: [ 'install', 'base64' ],
npm ERR! argv   original: [ 'install', 'base64' ] }
npm not ok

**Comment by Zenwolf** [comment]
oops, just saw this is a duplicate. I will close it. Thanks!

**Comment by pkrumins** [comment]
hi, i think the previous patch broke it. should work now.
