### ISSUE TITLE
Incorrect decoding - weird â characters

### ISSUE THREAD

**Issue by aslakhellesoy** [pkrumins/node-base64#4]
If you try to decode message.base64 in https://gist.github.com/763844 you get slightly wrong output. For example, "Itâs ghetto" is part of the decoded string, but it should be "It’s ghetto".

<pre>
var encoded = require('fs').readFileSync(__dirname + '/message.base64', 'ascii');
console.log(require('base64').decode(encoded));
</pre>

**Comment by pkrumins** [comment]
sorry, no idea.
