### ISSUE TITLE
base64 breaks npm install zombie.js ?

### ISSUE THREAD

**Issue by ghost** [pkrumins/node-base64#8]
Error: base64@1.0.1 install: `node-waf configure build`
npm ERR! `sh` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.2.16/package/lib/utils/exec.js:25:18)
npm ERR!     at ChildProcess.emit (events.js:45:17)
npm ERR!     at ChildProcess.onexit (child_process.js:171:12)
npm ERR! 
npm ERR! Failed at the base64@1.0.1 install script.
npm ERR! This is most likely a problem with the base64 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls base64
npm ERR! There may be additional logging output above.

**Comment by pkrumins** [comment]
Hi thanks for report but i have no idea at the moment.

**Comment by pkrumins** [comment]
sorry, no idea.
